### ISSUE TITLE
end is not highlighted if not surrounded by whitespace

### ISSUE THREAD

**Issue by sorawee** [samuela/language-pyret#4]
<img width="603" alt="screenshot 2016-05-14 17 17 44" src="https://cloud.githubusercontent.com/assets/9099577/15270740/d820048c-19f7-11e6-9ad9-182b468a4656.png">

Here, `end` should be highlighted.

**Comment by samuela** [comment]
Should be fixed now.

**Comment by samuela** [comment]
Thanks for the report!
